<?php
global $wpdb;

$talents = array(
  'liseyacoub@howmadareyou.com',
  'rimayacoub@howmadareyou.com',
  'pascalemonsef@cemotions.com',
  'pascalemonsef@howmadareyou.com',
  'pascalemounsef@gmail.com',
  'morgenstern@magic.fr',
  'rima@hyacoub.com',
  'rimayacoub@cemotions.com',
  'liseyacoub@cemotions.com',
  'latendremeute@gmail.com',
  'meligaz@hotmail.com',
  'emiliano.delorenzi@hotmail.com',
  'marwanantonios@gmail.com',
  'contact@cemotions.com',
  'juliencharlo@icloud.com',
  'amycamara25@gmail.com',
  'julien.kaalam@gmail.com',
  'pmscOc@yahoo.fr',
  'jonasdjian@gmail.com',
  'kirell@kirelion.com',
  'odvcrewmad@gmail.com',
  'salibiroula@gmail.com',
  'unity.movement@outlook.fr',
  'fguedon.pro@gmail.com',
  'philippe@fantascopeprod.com',
  'troubadoursswing@gmail.com',
  'nellafauve@gmail.com',
  'jd.baal@gmail.com',
  'klotilde.comedienne@gmail.com',
  'sofia_elkhyari@yahoo.fr',
  'shynissin@gmail.com',
  'jsilisty@gmail.com',
  'abbesses.musicpublishing@gmail.com',
  'v.zoeski@gmail.com',
  'thecoldkid@yahoo.com',
  'sralaia@yahoo.com',
  'valeyeya@hotmail.com',
  'booking.mab@gmail.com',
  'sacha.bitjocka@outlook.com',
  'gabriel.legrandmusicien@gmail.com',
  'thierry.chasselat@gmail.com',
  'camillebruat93@gmail.com',
  'solimeoboitepro@gmail.com',
  'heloise.haddad@gmail.com',
  'junecaravel@gmail.com',
  'rob@robincerutti.com',
  'jeanmarie.lavallee@free.fr',
  'contact@herveperdriel.com',
  'nella.schuss@gmail.com',
  'lequellec.caroline@hotmail.com',
  'tanny.onsalo@gmail.com',
  'shabycontact1@gmail.com',
  'jessie.bensimon@gmail.com',
  'poulain.artwork@gmail.com',
  'thibaultpinguet2@gmail.com',
  'jo.beauvois@gmail.com',
  'ange.fetochris@gmail.com',
  'b.gerbier@gmail.com',
  'nguyentayartist@gmail.com',
  'laurama.art@gmail.com',
  'sniktwo@hotmail.com',
  'hyakusbubble@gmail.com',
  'ashorphan@gmail.com',
  'nicolas.nargeot@orange.fr',
  'contact@lucieleguen.com',
  'chloeruchon@gmail.com',
  'gabartandco@gmail.com',
  'diane.painson@hotmail.fr',
  'kleinsylvain@gmail.com',
  'lino@linodivinci.com',
  'laureline.dalmau@gmail.com',
  'jennilly@hotmail.com',
  'lichevalierart@gmail.com',
  'drona.lala@gmail.com',
  'linestory@yahoo.com',
  'antoine.buttafoghi@orange.fr',
  'jenniferorhelys@gmail.com',
  'nour@nournajem.com',
  'manbicque@gmail.com',
  'alice.lebredonchel@gmail.com',
  'nadia.joynson@gmail.com',
  'sebastiengiray@gmail.com',
  'denisejabbour@gmail.com',
  'debelloy.claire@gmail.com',
  'ghayd@el3amaofficial.com',
  'fred-jacq@hotmail.com',
  'tarekmoukaddem@gmail.com',
  'cuxiecoo10@gmail.com',
  'belie.peintures@gmail.com',
  'thebambinojumbo@gmail.com',
  'music.eyra@yahoo.com',
  'info@1prcntarchitecture.com',
  'leo.thmlt@gmail.com',
  'rotolo.piero@hotmail.com',
  'philippekollo@hotmail.com',
  'durand.andrea@gmail.com',
  'anthony_fayad@live.com',
  'josselinrodrigues75@gmail.com',
  'contact@live124.com',
  'colinepagoda@gmail.com',
  'jacques@mashupcinema.com',
  'mozai@mozai.fr',
  'arrowstofire@gmail.com',
  'alexianoahg@gmail.com',
  'gregorystark75@gmail.com',
  'tendance3d.artdeco@gmail.com',
  'yara.saad94@hotmail.com',
  'samirmitri@icloud.com',
  'karl.r.dagher@gmail.com',
  'gracedesigncollection@gmail.com',
  'jadD@musician.org',
  'sam@ghobril.me',
  'joseph_zaitouny@hotmail.com',
  'hendrik.leyser@gmail.com',
  'aidatan01@hotmail.com',
  'aprilrach@gmail.com',
  'mohamadeldreini@gmail.com',
  'dany_saliba@hotmail.com',
  'neoninjmusic@gmail.com',
  'carl.ferneine@gmail.com',
  'tvvisuels@gmail.com',
  'larakaram9@gmail.com',
  'azizatofficial@gmail.com',
  'contact.vaslo@gmail.com',
  'ivaanyh@gmail.com',
  'james@jamesmpurpura.com',
  'josemanlius@gmail.com',
  'listeb2@gmail.com',
  'armagee.music@gmail.com',
  'vnussartiste@gmail.com',
  'fingerscrossedyse@gmail.com',
  'adrien.joly@gmail.com',
  'antoinestoenescu@gmail.com',
  'elioelbb@gmail.com',
  'ghadaghanem@gmail.com',
  'durev.prod@gmail.com',
  'perla.n.tanios@gmail.com',
  'yarakorkomaz@hotmail.com',
  'contact@atelierlux.fr',
  'fayabouhassan@gmail.com',
  'aurelienbuttin80@gmail.com',
  'ghida.knio@hotmail.com',
  '407@quatrecentsept.com',
  'jeanyvessaid@hotmail.fr',
  'david.djiango@gmail.com',
  'cosette.shedid@gmail.com',
  'mkwband@gmail.com',
  'l.hacquet@histoiresdl.com',
  'junjufi@gmail.com',
  'madelainevictor@gmail.com',
  'victorschegin@gmail.com',
  'sabbagha.enzo@gmail.com',
  'kaldeanakajima@gmail.com',
  'firasjhaidar@gmail.com',
  'maud_louvrier@yahoo.fr',
  'stephaniefikany@gmail.com',
  'mahdiasfahani27@gmail.com',
  'dahlia.nemlich@gmail.com',
  'deimian423@gmail.com',
  'younesstephanie@hotmail.com',
  'salloumrabih@gmail.com',
  'music.zef@gmail.com',
  'mariademian1@gmail.com',
  'sandyakoury98@gmail.com',
  'ralphabboud247@gmail.com',
  'hello@samah.xyz',
  'sr.makki@gmail.com',
  'annamariazoghby@gmail.com',
  'alanotayek@gmail.com',
  'jad_habchi@hotmail.com',
  'corinneskaff@gmail.com',
  'envisagesphotographie@gmail.com',
  'peckel17@gmail.com',
  'sandrineetbenoitpicot@gmail.com',
  'gaelle.cueff@orange.fr',
  'hellomaisonbernie@gmail.com',
  'gilqe@yahoo.fr',
  'contact@ookido.net',
  'alexis.c.dresco@hotmail.fr',
  'karam.georges7@gmail.com',
  'mai-mallet@hotmail.fr',
  'lea-marion@hotmail.fr',
  'blindancedate@gmail.com',
  'ylda.decrop@outlook.com',
  'ayoub.khm@hotmail.fr',
  'braka@netcourrier.com',
  'alvaro.chatin@hotmail.com',
  'sabineraymond@icloud.com',
  'e.grenier.lightworks@free.fr',
  'tpegeon@gmail.com',
  'majdo.concert@gmail.com',
  'danyraedhawa@gmail.com',
  'sarahjacquier01@gmail.com',
  'celia.blum@hotmail.fr',
  'clain@ursidaeparis.com',
);



/*$all_users = $wpdb->get_results("SELECT * FROM {$wpdb->prefix}users");

foreach ($all_users as $user):
  if(in_array($user->user_email, $talents)):
    update_user_meta($user->ID, 'waiting', true);
    update_user_meta($user->ID, 'waiting_date', date('Y-m-d h:i:s'));
  endif;
endforeach;*/

$dsn = 'mysql:dbname=test;host=yl5435-001.privatesql:35495';
$user = 'braveart2010';
$password = 'Jesuisfou2019';

function _uploadImageToMediaLibrary($postID, $url, $alt = "") {
    require_once(ABSPATH . "wp-admin" . '/includes/image.php');
    require_once(ABSPATH . "wp-admin" . '/includes/file.php');
    require_once(ABSPATH . "wp-admin" . '/includes/media.php');

    $tmp = download_url( $url );
    $desc = $alt;
    $file_array = array();

    // Set variables for storage
    // fix file filename for query strings
    preg_match('/[^\?]+\.(jpg|jpe|jpeg|gif|png)/i', $url, $matches);
    $file_array['name'] = basename($matches[0]);
    $file_array['tmp_name'] = $tmp;

    // If error storing temporarily, unlink
    if ( is_wp_error( $tmp ) ) {
        @unlink($file_array['tmp_name']);
        $file_array['tmp_name'] = '';
    }

    // do the validation and storage stuff
    $id = media_handle_sideload( $file_array, $postID, $desc);

    // If error storing permanently, unlink
    if ( is_wp_error($id) ) {
        @unlink($file_array['tmp_name']);
        return $id;
    }

    return $id;
}

try {
  $bdd = new PDO($dsn, $user, $password);
}
catch (PDOException $e) {
  echo 'Connexion échouée : ' . $e->getMessage();
}

$sql = "SELECT * FROM MAD_posts WHERE post_type='ignition_product' AND post_status = 'publish'";
$index = 0;

/*
$all_user_email = array(
  'veronique.spitzer@orange.fr',
  'christian@yacandco.fr',
  'tyveklathe80269@hotmail.com',
  'clairebchabert@gmail.com',
  'louise.podmoutard@gmail.com',
  'alexandre.fiocre@gmail.com',
  'franckdewannieux@howmadareyou.com',
  'royaurelie@yahoo.fr',
  'liseyacoub@hotmail.com',
  'farbadge45@live.com',
  'eliashaber@live.com',
  'skitzokronicles@gmail.com',
  'armada.12.jdo@gmail.com',
  'julianabdelhak@gmail.com',
  'hugowaitzmann@hotmail.fr',
  'murderdancemachine@gmail.com',
  'gregory.lamothe@sfr.fr',
  'justineberner@gmail.com',
  'nada.otayek@gmail.com',
  'sleboulch@gmail.com',
  'hlne.lucien@gmail.com',
  'amr3k@hotmail.com',
  'eliashaddad988@hotmail.com',
  'khalifalavy43@gmail.com',
  'phat2@reborn.com',
  'dj.johnmagus@gmail.com',
  'nemer.abbas.lb@gmail.com',
  'booking.catalysia@gmail.com',
  'fsailabouni@ndu.edu.lb',
  'taniaiskandar7@gmail.com',
  'samersarkis@live.com',
  'naman912000@gmail.com',
  'chantalabboud101@gmail.com',
  'mirachoukeir@gmail.com',
  'roulakl09@hotmail.com',
  'mojojamz@gmail.com',
  'wissam.matar@gmail.com',
  'najlamaatouk@gmail.com',
  'tawilanthony@gmail.com',
  'samirsyriani@gmail.com',
  'tawilteddy@gmail.com',
  'anthony.sahyoun@gmail.com',
  'marietermignon@hotmail.fr',
  'louise.elizeon@gmail.com',
  'ingridhage17@gmail.com',
  'elammhala@gmail.com',
  'renee.liber8ed@gmail.com',
  'mayyasaliba@gmail.com',
  'fidele.hage@gmail.com',
  'noormounzer@hotmail.com',
  'abouchabkejoelle6@gmail.com',
  'avo.deronian@gmail.com',
  'dalia_f_10@hotmail.com',
  'ateliertulipenoire@gmail.com',
  'jessica.e.ghoul@gmail.com',
  'evangeloabb@hotmail.com',
  'lynnkhoury@hotmail.com',
  'daspampa.emergenciacreativa@gmail.com',
  'fares.farhat@hotmail.com',
  'daherghinwa@gmail.com',
  'xtian.wehbe@hotmail.com',
  'marie_lynes@hotmail.com',
  'sandrojazzar@gmail.com',
  'sargon@hyacoub.com',
  'mekhaelmaher@gmail.com',
  'janemichelgay@gmail.com',
  'chouchou_1010@hotmail.fr',
  'coutarel.julie@gmail.com',
  'noemie.guillemin@yahoo.fr',
  'elvinaranguin@gmail.com',
  'gregnigoghossian@gmail.com',
  'camille.guillot971@gmail.com',
  'lulu.lr92@gmail.com',
  'drakosha_new@aol.com',
  'pounde21@hotmail.fr',
  'asmabevilacqua@gmail.com',
  'rocco-morello@hotmail.fr',
  'josechalita@hotmail.fr',
  'clea.polar@gmail.com',
  'rakoto_sahondra@yahoo.fr',
  'aando79@gmail.com',
  'poupee_2_soie@yahoo.fr',
  'chimene.delayre@sfr.fr',
  'kniego@greenraid.fr',
  'wd.decarvalho@wanadoo.fr',
  'edithbabik@hotmail.com',
  'edithbabik@hotmail.com',
  'carla.aouad@gmail.com',
  'eyqzbadap@popp.eamale.com',
  'ixnawyi@mail.eamale.com',
  'ikagoyipt@popp.eamale.com',
  'ogohenw@mail.eamale.com',
  'adoczil@popp.eamale.com',
  'ejyisaj@popp.eamale.com',
  'nad.calme@gmail.com',
  'misslaetitiawatson@gmail.com',
  'pauulineengel@gmail.com',
  'laromaniere@gmail.com',
  'raphael.grolleaull@gmail.com',
  'gulsum.kalabey@gmail.com',
  'zantchevski@mail.ru',
  'helena_fronczak@hotmail.fr',
  'oscargaudelette@gmail.com',
  'ktiouetcharafa@gmail.com',
  'aureliemuzette@yahoo.fr',
  'quentin.maurion@kedgebs.com',
  'lazy_soul@hotmail.fr',
  'joannes.stephanie@gmail.com',
  'quentin.grau7@gmail.com',
  'contact.samueldidi@gmail.com',
  'mc-pimousse@hotmail.fr',
  'thibaudeudier@yahoo.fr',
  'vinetbastien@gmail.com',
  'roussou_karolina@yahoo.fr',
  'lagrandesandra@gmail.com',
  'a.mele90@hotmail.fr',
  'ilan.david@live.fr',
  'pialaugier@gmail.com',
  'clementine1805@gmail.com',
  'anascastillon@ymail.com',
  'quentin.daussy@gmai.com',
  'alexcoh01@gmail.com',
  'raphaelginestet@yahoo.fr',
  'info@apeloig.com',
  'vincent.soave@kedgebs.com',
  'susanoo.soave@gmail.com',
  'facourtioux@hotmail.fr',
  'nadia.zvorykin@gmail.com',
  'margaux.gaudron@hotmail.fr',
  'vincent_thery5@hotmail.com',
  'gab119@icloud.com',
  'suziedelaine@gmail.com',
  'titouschricke@hotmail.fr',
  'tania.elisa.marie@gmail.com',
  'minisculeart@gmail.com',
  'lezard_007@hotmail.fr',
  'syma.mati@gmail.com',
  'indra.hage@gmail.com',
  'pdaguise_cdp@club-internet.fr',
  'neb611@hotlail.com',
  'elena_motuz@hotmail.com',
  'y_boutros@hotmail.com',
  'mzungoo@googlemail.com',
  'toffifee29@gmail.com',
  'redoakboo@embarqmail.com',
  'direction@bo-prod.com',
  'bwaitzmann@gmail.com',
  'c.ktiouet@hotmail.fr',
  'cat_eye_92@hotmail.com',
  'chadykarlitch@gmail.com',
  'debar.matthis@outlook.com',
  'pricev@derm.ucsf.edu',
  'info@almaco.com.ua',
  'pascal@bruandet.eu',
  'hi.i.m.ma.rcus.@artemmel.info',
  'jolynn.briggs@cincindustries.com',
  'beainy@hotmail.com',
  'liseyacoub@gmail.com',
  'sarahlee.merheb@gmail.com',
  'rabih.eldarwiche@hotmail.com',
  'talinekanledjian@gmail.com',
  'julien.psg78240@gmail.com',
  'karim.schams@gmail.com',
  'ahmadomary24@gmail.com',
  'azdirection@hotmail.com',
  'fadiabbas43@hotmail.com',
  'qsun.contact@gmail.com',
  'zaher.beaini@hotmail.com',
  'gmkhalaf@gmail.com',
  'kamehhussein@gmail.com',
  'jimmylulendo97@gmail.com',
  'starpat800@gmail.com',
  'holyjukeboxband@gmail.com',
  'joy.hoyek@live.com',
  'ahmed.baltaji@itsbeirut.com',
  'marc-basset@hotmail.com',
  'lama.hatoum29@gmail.com',
  'elie.tekle@hotmail.com',
  'saaderalph@gmail.com',
  'marc.g.gemayel@gmail.com',
  'stevensemaan@hotmail.com',
  'husseinalabdallah6@gmail.com',
  'rebeccazgheib123@gmail.com',
  'kostantinechadi@hotmail.com',
  'noursalem1@hotmail.com',
  'films.toya@gmail.com',
  'joegerges@outlook.com',
  'che_spree8@hotmail.com',
  'raymondjoseph.asmar@gmail.com',
  'seropiansako@gmail.com',
  'maysounhilal@hotmail.com',
  'estephandiana@gmail.com',
  'rita.el.kazzi@hotmail.com',
  'leilamacaire@gmail.com',
  'nrouhana@im-capital.com',
  'housseinhammoud56@gmail.com',
  'karam.wahab.kw@gmail.com',
  'd.jarjour@hotmail.com',
  'sergemajdalany@gmail.com',
  'mallahceline@gmail.com',
  'sharif_haddad@hotmail.com',
  'abbass.beydoun@gmail.com',
  'radwan.k.hasan95@gmail.com',
  'abdoul224488888888@hotmail.com',
  'feyrouz.a.h@gmail.com',
  'twixx_twin@hotmail.com',
  'marcel_saad@hotmail.com',
  'pam-elias@hotmail.com',
  's3d.masri@gmail.com',
  'greciaantoun@hotmail.com',
  'mohamed.yaghy@gmail.com',
  'lavedesign@outlook.com',
  'moelattouf2016@gmail.com',
  'diminassar@gmail.com',
  'abdelrah@gmail.com',
  'joegoodb@gmail.com',
  'romain.joveneau@gmail.com',
  'eleehelou@gmail.com',
  'rita_baaklini@hotmail.com',
  'naderabdelrahim@gmail.com',
  'lily@dynamicrecruit.com',
  'brunowaitzmann@howmadareyou.com',
  'georgesmradmrad@hotmail.com',
  'zaidanv@hotmail.com',
  'mohammadhalabi1@hotmail.com',
  'meyssi_abboud@windowslive.com',
  'rita_karam.9.a@hotmail.com',
  'ginasalamh@gmail.com',
  'supanao@hotmail.fr',
  'zekatjookin@gmail.com',
  'vckingzcrew@gmail.com',
  'gabriel.mabilat@gmail.com',
  'charles.challita@hotmail.com',
  'eloi-fg@gmx.com',
  'ntoyiartist@gmail.com',
  'mathieu.jankowiak@gmail.com',
  'maryse.campion33@gmail.com',
  'cdayou@yahoo.fr',
  'trash@julsboo.fr',
  'camillou-sxm@hotmail.fr',
  'piieceofficiel@gmail.com',
  'patrice@quixotemusic.eu',
  'sdemeurville@wanadoo.fr',
  'metais.antoine@gmail.com',
  'maylisdekerangal@noos.fr',
  'jprevos123@gmail.com',
  'orakl@howmadareyou.com',
  'v.h@rivercoach.fr',
  'paulineengel@hotmail.fr',
  'lolaaumont.doc@gmail.com',
  'jeromebloch@crea-films.com',
  'th@arditti.org',
  'p.gc@live.fr',
  'bethsgabbay@gmail.com',
  'magenta@chloemaillard.fr',
  'schan@deltaensemble.org',
  'cdelorme17@gmail.com',
  'cl.verillaud@gmail.com',
  'clmntgbrt@gmail.com',
  'joanne.rkt@gmail.com',
  'hbrunet2011@gmail.com',
  'o.pernet@libertysurf.fr',
  'timothee.caumartin@gmail.com',
  'yohan.saynac@gmail.com',
  'aslexim@gmail.com',
  'charles.buskavida@gmail.com',
  'vix.end.official@gmail.com',
  'kirellou@gmail.com',
  'gildas.lointier@free.fr',
  'pierre.com.ca@gmail.com',
  'maur.anne.griffonnet@gmail.com',
  'm8.adjovi@gmail.com',
  'raoul.tchoi@hotmail.fr',
  'hitman5304@gmail.com',
  'djena98@live.fr',
  'n.diaye_aida@yahoo.fr',
  'qweensydjee@gmail.com',
  'jeanmarc.muller@wanadoo.fr',
  'juliette.ensuque@sfr.fr',
  'wdelcour@hotmail.com',
  'erwan.agh@gmail.com',
  'dargaaanis@gmail.com',
  'constantin.katia@gmail.com',
  'celine.larochelle@orange.fr',
  'erk@erkmusic.fr',
  'bordesvero@gmail.com',
  'franka.huynh@gmail.com',
  'mel.gehant@gmail.com',
  'pauline_drion@hotmail.com',
  'clothilde.fayol@gmail.com',
  'oceane-30@live.fr',
  'coeur-julien@outlook.fr',
  'lou.pro@outlook.com',
  'alexis.cmb@gmail.com',
  'g.crochet@live.fr',
  'thomas.douart@gmail.com',
  'clemtawaa@gmail.com',
  'rocheestelle@hotmail.com',
  'kirszbaum.v@gmail.com',
  'maylia.arn@gmail.com',
  'iamiboamn@gmail.com',
  'contact@ameliechassary.com',
  'luc.perdriel@hotmail.fr',
  'vincent.hamon70@gmail.com',
  'volodia.panak@gmail.com',
  'erellqr@gmail.com',
  'jacqueline.lointier@free.fr',
  'celine.dinant@gmail.com',
  'a.faure@unimev.fr',
  'c.marsilli@unimev.fr',
  'hadrien.mabilat@laposte.net',
  'gmepage@laposte.net',
  'anton.lik@hotmail.fr',
  'mylene.grau@gmail.com',
  'wilfrid.roth@gmail.com',
  'ethelran@gmail.com',
  'cclauss18@gmail.com',
  'pierrecolse@hotmail.fr',
  'mat.cav@hotmail.fr',
  'gabriel.mabilat@laposte.net',
  'doriakarine@gmail.com',
  'nutritiongeoffroy@gmail.com',
  'virginie.haaz@gmail.com',
  's.tripierrollin@gmail.com',
  'baby.kani@hotmail.fr',
  'jade.boinet@laposte.net',
  'angeljunes2005@gmail.com',
  'evenementielartistique@artistrip.com',
  'lancelotharistoy@gmail.com',
  'rosine.makhlouf@gmail.com',
  'greg@lalegendedessinee.com',
  'gamausno@gmail.com',
  'paryswilliam@gmail.com',
  'valerie_merveille@yahoo.fr',
  'avera@tradelab.fr',
  'camille.richon@fuseint.com',
  'colomba.jub@gmail.com',
  'rollin.christiane@yahoo.fr',
  'paulineh.roche@gmail.com',
  'zenatoffice@gmail.com',
  'melanie.welklen@gmail.com',
  'lesdessinsdesophieb@gmail.com',
  'cedriclebris56@gmail.com',
  'thachvanessa@gmail.com',
  'instanseizi@gmail.com',
  'iris.schalamon1@gmail.com',
  'audreydubourg@gmail.com',
  'matthieu.goussot@urssaf.fr',
  'deborah.dechamps@civis.fr',
  'azambre.luc@gmail.com',
  'jeanlouis.tripier@gmail.com',
  'vivilualar@gmail.com',
  'marion.dictus@gmail.com',
  'michellereclair@gmail.com',
  'madice75@hotmail.fr',
  '222torresanalaura@gmail.com',
  'zolfra@gmail.com',
  'jeromebloux@gmail.com',
  'lucilleboitelle@iceho.fr',
  'matelotnicolas@gmail.com',
  'cedricurbaniak@outlook.fr',
  'bastian@ereimul.com',
  'jaelle.boucah@gmail.com',
  'debolucie.nakache@gmail.com',
  'auroresaintbris@gmail.com',
  'stephanie.ledroit@gmail.com',
  'rzin.salma@gmail.com',
  'jenniferbruget@gmail.com',
  'eleonore.heftlerlouiche@gmail.com',
  'wlauret@gmail.com',
  'etiennejonget@gmail.com',
  'p.landais-barrau@cnewsmatin.net',
  'contact@gabrielkishan.com',
  'luscens@free.fr',
  'ljuliol@hotmail.com',
  'juliemirasola@yahoo.fr',
  'stephanie.realdelsarte@gmail.com',
  'frankmer@free.fr',
  'emarounpainting@gmail.com',
  'presse@dillinger.fr',
  'artoville@gmail.com',
  'schneideralexandra92260@hotmail.fr',
  'bujix@hotmail.fr',
  'alexiagaud@hotmail.fr',
  'anthony23mdt@gmail.com',
  'bencube03@gmail.com',
  'antoine.detavernost@gl-events.com',
  'correiasilvamarvin@hotmail.fr',
  'julescolin90@hotmail.fr',
  'lougaujal@gmail.com',
  'bencube01@gmail.com',
  'audrey.nakache@gmail.com',
  'seb.viguier@laposte.net',
  'josephinevallee@hotmail.com',
  'dotty.contact@gmail.com',
  'ferdinand.delaubier@gmail.com',
  'ma.laura@hotmail.fr',
  'jaelleboucah@gmail.com',
  'contact@florissexgermain.com',
  'contact@virginievaz-photo.com',
  'hugo.venturini@gmail.com',
  'contact@maxledieu.com',
  'info@theartofneo.com',
  'rolle.chloe@gmail.com',
  'jeansakr85@gmail.com',
  'vricheux@wanadoo.fr',
  'rachidouadah@gmail.com',
  'laurine.grs12@gmail.com',
  'elovaia@yahoo.fr',
  'royer99@free.fr',
  'mat.jouen@gmail.com',
  'elisadesbrosses@gmail.com',
  'fanny.moreau5@wanadoo.fr',
  'alix.debleue@gmail.com',
  'cam.delzanni@hotmail.fr',
  'carp.ben@wanadoo.fr',
  'julie.victoire.boban@gmail.com',
  'boussad.hallou@gmail.com',
  'pirot.thomas@gmail.com',
  'golnazpyn@gmail.com',
  'iceglock.pro@gmail.com',
  'zkostic04@gmail.com',
  'mariondem@gmail.com',
  'marine.goodmorning@hotmail.fr',
  'victoriageremie@gmail.com',
  'lucille.boitelle@yahoo.fr',
  'misterng@hotmail.fr',
  'juliette.seban@gmail.com',
  'pivet.aurelie@hotmail.fr',
  'siglen.vlx@gmail.com',
  'carodarty@yahoo.fr',
  'aubjul@laposte.net',
  'rminidriss@live.fr',
  'contact@msgarciaphotography.com',
  'francoisbachellerie@gmail.com',
  'noliboisalice@gmail.com',
  'kermapaul@gmail.com',
  'p.c.marilou@gmail.com',
  'jennifer.cammaroto@hotmail.fr',
  'alizedum@hotmail.fr',
  'dutempleg@yahoo.fr',
  'ameliechassary@gmail.com',
  'nclslbrn@gmail.com',
  'savina.ivaylova.topurska@gmail.com',
  'louise.gaucher@gmail.com',
  'bluedechine@live.fr',
  'karine.trul1@gmail.com',
  'laura.porzio16@gmail.com',
  'abkmontmartre@gmail.com',
  'nejadplus@dbmail.com',
  'keosanva@gmail.com',
  'emiliemoutsis@gmail.com',
  'izzzzabelle@gmail.com',
  'camilaballenghien@hotmail.com',
  'harasdemartinvast@yahoo.com',
  'brigitteosmont@yahoo.fr',
  'nolwenn89@hotmail.fr',
  'vivi_34110@hotmail.fr',
  'cesarkaci@hotmail.fr',
  'mecdg0@gmail.com',
  'info@valeriajaramillo.com',
  'jeromelanger5@gmail.com',
  'contact@basaltink.com',
  'r.virgile@hotmail.fr',
  'edelvia1@gmail.com',
  'pouspoush@hotmail.fr',
  'ancelfranck@gmail.com',
  'c.worner@free.fr',
  'charlotte.vitaioli@gmail.com',
  'eulai@hotmail.fr',
  'zabou.m@free.fr',
  'elitsaes@yahoo.fr',
  'virginierose88@gmail.com',
  'info@martinleveque.com',
  'malardenti@wanadoo.fr',
  'contact@ailo.fr',
  'beope@yahoo.com',
  'alexandra.breznay@gmail.com',
  'alena.carbonel@hotmail.fr',
  'gllm.descamps@gmail.com',
  'contact@lerobin.com',
  'mehdibenkaci@gmail.com',
  'bubboncoli@gmail.com',
  'kristen.xia14@gmail.com',
  'asberthet@hotmail.fr',
  'mourad_sport@hotmail.fr',
  'julieandrieu96@gmail.com',
  'orgascidiae@gmail.com',
  'solimeomathilde@gmail.com',
  'dahbiakhamsanegadi@gmail.com',
  'agathe.miellot@gmail.com',
  'lud.artwork@gmail.com',
  'littlebiglilit@gmail.com',
  'aurore.nardot@hotmail.com',
  'gauthierlecavelier@gmail.com',
  'marie.dumont8@gmail.com',
  'martial_j@hotmail.com',
  'quentin.daussy@gmail.com',
  'ophelie.jsan@gmail.com',
  'thomas.poncelet@essec.edu',
  'hamza.yassine@hotmail.com',
  'band@wakeislandmusic.com',
  'stephy83_4@hotmail.com',
  'huma.positifs@gmail.com',
  'philippeachard@me.com',
  'cemfilitti@gmail.com',
  'eylia.t@hotmail.fr',
  'cinefoxlive@gmail.com',
  'info@mygeektech.net',
  'florian.martinezlopez@gmail.com',
  's.yeramian@hotmail.fr',
  'mathieujankowiak@howmadareyou.com',
  'frederic@haire.fr',
  'martinelli.helene@gmail.com',
  'sydneywriter@gmail.com',
  'camaraamy@hotmail.fr',
  'imran7@hotmail.fr',
  'tran_helene3@hotmail.com',
  'ndc.renata@gmail.com',
  'mayssa.as.otayek@gmail.com',
  'elvisattack.prensa@gmail.com',
  'contact@artichaut-records.com',
  'juliedousset@gmail.com',
  'fadi.t.m.haroun@gmail.com',
  'bonsoirmacadam@gmail.com',
  'jason.rolland10@gmail.com',
  'magdalenam@naver.com',
  'leo_77_@hotmail.fr',
  'maferrat@free.fr',
  'contact.yonn@gmail.com',
  'megane.danican@hotmail.fr',
  'sunrizeent@gmail.com',
  'designal@live.fr',
  'salmakandilart@gmail.com',
  'maree.guillemet@gmail.com',
  'bialy.rebecca@gmail.com',
  'ntuf@hotmail.com',
  'wallaceetyoumi@gmail.com',
  'khalifeh.cynthia@gmail.com',
  'info@cynthiakhalifeh.com',
  'gabaris@hotmail.fr',
  'oliviercasado@gmail.com',
  'clara-meysen@hotmail.fr',
  'cherrinola@gmail.com',
  'cyrillea777@gmail.com',
  'illegy.music@gmail.com',
  'manon.buttaro@gmail.com',
  'claraacm3@gmail.com',
  'suhail.khoury@me.com',
  'andrebielen@yahoo.fr',
  'myrtille.neimann@hotmail.com',
  'capuflower@live.fr',
  'ralphnabhan@gmail.com',
  'talaladki@howmadareyou.com',
  'joumanaboufakhreddine@gmail.com',
  'info@letmeship.com',
  'kouadioessy@outlook.fr',
  'tareksina@gmail.com',
  'aurore404records@gmail.com',
  'ishtar.abidaher@gmail.com',
  'fossierg@gmail.com',
  'xlpnrvsgqd_1541428725@tfbnw.net',
  'uabulbtimq_1540975700@tfbnw.net',
  'victoriatodorovpro@gmail.com',
  'quentin.daussy@kedgebs.com',
  'audidiane@gmail.com',
  'elienjeim87@gmail.com',
  'h.serge.i.ghazale.v.22@gmail.com',
  'contact@ysbd.fr',
  'johnp@apbconstructiongroup.com',
  'nicolas@notasite.fr',
  'kaldeanakajima@googlemail.com',
  'fred.perriot@gmail.com',
  'a.orsho@hotmail.com',
  'zeaiterelio@gmail.com',
  'rom1wagner@gmail.com',
  'canisvezania@gmail.com',
  'hoffenbergv@hotmail.fr',
  'fingerscrossedys@gmail.com',
  'vnipfrikah_1541428725@tfbnw.net',
  'nagham_helou@live.com',
  'juliechevalier.contact@gmail.com',
  'rememberchaban@gmail.com',
  'ryo.sakuto@protonmail.com',
  'louislekim@gmail.com',
  'serabiancristine@gmail.com',
  'a.mora-william@gmx.com',
  'contact@montrealradiocite.com',
  'virmace_1@hotmail.com',
  'rocknkarolyne@gmail.com',
  'floriandidier@howmadareyou.com',
  'ynelsaitham@gmail.com',
  'cyrilhavart@yahoo.fr',
  'by.sirindogus@gmail.com',
  'nathaliecaruso1977@gmail.com',
  'chloeruchon@hotmail.fr',
  'evah_rock@hotmail.com',
  'souslalune@laposte.net',
  'sebastien-voignier@live.fr',
  'nicolas@nextoneagency.com',
  'contact@stephanie-mackenzie.com',
  'vgoricanec@orange.fr',
  'mariem.minot@gmail.com',
  'alexandraberthome@gmail.com',
  'gilqe@yahoo.fr',
  'm-clara@live.fr',
  'benoit.picot@orange.fr',
  'funambule.v@gmail.com',
  'freddiebollet@gmail.com',
  'krys13800@gmail.com',
  'clairecolincollection@gmail.com',
  'sarin.vos@gmail.com',
  'hanigholam@gmail.com',
  'juliettejabra@gmail.com',
  'landl_fashion@yahoo.com',
  'soazigbouvet@gmail.com',
  'jorgelina@orange.fr',
  'hello@roseincorporated.net',
  'j.soumoy@strate.design',
  'dobrzelewski.sca@gmail.com',
  'alzein_jad@hotmail.com',
  'rarrout@hotmail.com',
  'xriss.jor@gmail.com',
  'rita.p.irany@gmail.com',
  'ralph.e.abboud@gmail.com',
  'charbel.sawma7@gmail.com',
  'jessica.bounni@gmail.com',
  'moerashid61@gmail.com',
  'lisa.lorbeer@web.de',
  'louay.daoust91@gmail.com',
  'larajtrad@gmail.com',
  'namgi.kemis@gmail.com',
  'wassim.n.ch@gmail.com',
  'geogatedproject212@gmail.com',
  'ramya.chuon@gmail.com',
  'mahre.buckham@live.fr',
  'florentnaranjo.elu@gmail.com',
  'sm.chloeep@outlook.com',
  'lecatelierlaura@gmail.com',
  'remi.lufuta@gmail.com',
  'mariegontier@yahoo.fr',
  'tcherkasovat@gmail.com',
  'laurie.bisceglia@gmail.com',
  'rabbas@wixelstudios.com',
  'c.calassou@laposte.net',
  'wilhelm_amelie@yahoo.fr',
  'tomlecocguen@hotmail.fr',
  'jenna_cohen@msn.com',
  'bjh.nizar@gmail.com',
  'geogatedproject252@gmail.com',
  'geogatedproject281@gmail.com',
  'rouvrez@sfr.fr',
  'newbi_only@hotmail.fr',
  'annieehrsam@live.fr',
  'aymeric.dechin@gmail.com',
  'souhailkhoury@gmail.com',
  'm-clara-m@live.fr',
  'amornanwjn_1573462166@tfbnw.net',
  'bonnieboxe@gmail.com',
  'rosemorgan.aci@gmail.com',
  'jana-saade@live.com',
  'ophelie.spodobalskipro@gmail.com',
  'noel.alashahan@gmail.com',
  'help@howmadareyou.com',
  'liseyacoub@howmadareyou.com',
  'rimayacoub@howmadareyou.com',
  'pascalemonsef@cemotions.com',
  'pascalemonsef@howmadareyou.com',
  'pascalemounsef@gmail.com',
  'morgenstern@magic.fr',
  'rima@hyacoub.com',
  'rimayacoub@cemotions.com',
  'liseyacoub@cemotions.com',
  'latendremeute@gmail.com',
  'meligaz@hotmail.com',
  'emiliano.delorenzi@hotmail.com',
  'marwanantonios@gmail.com',
  'contact@cemotions.com',
  'juliencharlo@icloud.com',
  'amycamara25@gmail.com',
  'julien.kaalam@gmail.com',
  'pmscoc@yahoo.fr',
  'jonasdjian@gmail.com',
  'kirell@kirelion.com',
  'odvcrewmad@gmail.com',
  'salibiroula@gmail.com',
  'unity.movement@outlook.fr',
  'fguedon.pro@gmail.com',
  'philippe@fantascopeprod.com',
  'troubadoursswing@gmail.com',
  'nellafauve@gmail.com',
  'jd.baal@gmail.com',
  'klotilde.comedienne@gmail.com',
  'sofia_elkhyari@yahoo.fr',
  'shynissin@gmail.com',
  'jsilisty@gmail.com',
  'abbesses.musicpublishing@gmail.com',
  'v.zoeski@gmail.com',
  'thecoldkid@yahoo.com',
  'sralaia@yahoo.com',
  'valeyeya@hotmail.com',
  'booking.mab@gmail.com',
  'sacha.bitjocka@outlook.com',
  'gabriel.legrandmusicien@gmail.com',
  'thierry.chasselat@gmail.com',
  'camillebruat93@gmail.com',
  'solimeoboitepro@gmail.com',
  'heloise.haddad@gmail.com',
  'junecaravel@gmail.com',
  'rob@robincerutti.com',
  'jeanmarie.lavallee@free.fr',
  'contact@herveperdriel.com',
  'nella.schuss@gmail.com',
  'lequellec.caroline@hotmail.com',
  'tanny.onsalo@gmail.com',
  'shabycontact1@gmail.com',
  'jessie.bensimon@gmail.com',
  'poulain.artwork@gmail.com',
  'thibaultpinguet2@gmail.com',
  'jo.beauvois@gmail.com',
  'ange.fetochris@gmail.com',
  'b.gerbier@gmail.com',
  'nguyentayartist@gmail.com',
  'laurama.art@gmail.com',
  'sniktwo@hotmail.com',
  'hyakusbubble@gmail.com',
  'ashorphan@gmail.com',
  'nicolas.nargeot@orange.fr',
  'contact@lucieleguen.com',
  'chloeruchon@gmail.com',
  'gabartandco@gmail.com',
  'diane.painson@hotmail.fr',
  'kleinsylvain@gmail.com',
  'lino@linodivinci.com',
  'laureline.dalmau@gmail.com',
  'jennilly@hotmail.com',
  'lichevalierart@gmail.com',
  'drona.lala@gmail.com',
  'linestory@yahoo.com',
  'antoine.buttafoghi@orange.fr',
  'jenniferorhelys@gmail.com',
  'nour@nournajem.com',
  'manbicque@gmail.com',
  'alice.lebredonchel@gmail.com',
  'nadia.joynson@gmail.com',
  'sebastiengiray@gmail.com',
  'denisejabbour@gmail.com',
  'debelloy.claire@gmail.com',
  'ghayd@el3amaofficial.com',
  'fred-jacq@hotmail.com',
  'tarekmoukaddem@gmail.com',
  'cuxiecoo10@gmail.com',
  'belie.peintures@gmail.com',
  'thebambinojumbo@gmail.com',
  'music.eyra@yahoo.com',
  'info@1prcntarchitecture.com',
  'leo.thmlt@gmail.com',
  'rotolo.piero@hotmail.com',
  'philippekollo@hotmail.com',
  'durand.andrea@gmail.com',
  'anthony_fayad@live.com',
  'josselinrodrigues75@gmail.com',
  'contact@live124.com',
  'colinepagoda@gmail.com',
  'jacques@mashupcinema.com',
  'mozai@mozai.fr',
  'arrowstofire@gmail.com',
  'alexianoahg@gmail.com',
  'gregorystark75@gmail.com',
  'tendance3d.artdeco@gmail.com',
  'yara.saad94@hotmail.com',
  'samirmitri@icloud.com',
  'karl.r.dagher@gmail.com',
  'gracedesigncollection@gmail.com',
  'jadD@musician.org',
  'sam@ghobril.me',
  'joseph_zaitouny@hotmail.com',
  'hendrik.leyser@gmail.com',
  'aidatan01@hotmail.com',
  'aprilrach@gmail.com',
  'mohamadeldreini@gmail.com',
  'dany_saliba@hotmail.com',
  'neoninjmusic@gmail.com',
  'carl.ferneine@gmail.com',
  'tvvisuels@gmail.com',
  'larakaram9@gmail.com',
  'azizatofficial@gmail.com',
  'contact.vaslo@gmail.com',
  'ivaanyh@gmail.com',
  'james@jamesmpurpura.com',
  'josemanlius@gmail.com',
  'listeb2@gmail.com',
  'armagee.music@gmail.com',
  'vnussartiste@gmail.com',
  'fingerscrossedyse@gmail.com',
  'adrien.joly@gmail.com',
  'antoinestoenescu@gmail.com',
  'elioelbb@gmail.com',
  'ghadaghanem@gmail.com',
  'durev.prod@gmail.com',
  'perla.n.tanios@gmail.com',
  'yarakorkomaz@hotmail.com',
  'contact@atelierlux.fr',
  'fayabouhassan@gmail.com',
  'aurelienbuttin80@gmail.com',
  'ghida.knio@hotmail.com',
  '407@quatrecentsept.com',
  'jeanyvessaid@hotmail.fr',
  'david.djiango@gmail.com',
  'cosette.shedid@gmail.com',
  'mkwband@gmail.com',
  'l.hacquet@histoiresdl.com',
  'junjufi@gmail.com',
  'madelainevictor@gmail.com',
  'victorschegin@gmail.com',
  'sabbagha.enzo@gmail.com',
  'kaldeanakajima@gmail.com',
  'firasjhaidar@gmail.com',
  'maud_louvrier@yahoo.fr',
  'stephaniefikany@gmail.com',
  'mahdiasfahani27@gmail.com',
  'dahlia.nemlich@gmail.com',
  'deimian423@gmail.com',
  'younesstephanie@hotmail.com',
  'salloumrabih@gmail.com',
  'music.zef@gmail.com',
  'mariademian1@gmail.com',
  'sandyakoury98@gmail.com',
  'ralphabboud247@gmail.com',
  'hello@samah.xyz',
  'sr.makki@gmail.com',
  'annamariazoghby@gmail.com',
  'alanotayek@gmail.com',
  'jad_habchi@hotmail.com',
  'corinneskaff@gmail.com',
  'envisagesphotographie@gmail.com',
  'peckel17@gmail.com',
  'sandrineetbenoitpicot@gmail.com',
  'gaelle.cueff@orange.fr',
  'hellomaisonbernie@gmail.com',
  'gilqe@yahoo.fr',
  'contact@ookido.net',
  'alexis.c.dresco@hotmail.fr',
  'karam.georges7@gmail.com',
  'mai-mallet@hotmail.fr',
  'lea-marion@hotmail.fr',
  'blindancedate@gmail.com',
  'ylda.decrop@outlook.com',
  'ayoub.khm@hotmail.fr',
  'braka@netcourrier.com',
  'alvaro.chatin@hotmail.com',
  'sabineraymond@icloud.com',
  'e.grenier.lightworks@free.fr',
  'tpegeon@gmail.com',
  'majdo.concert@gmail.com',
  'danyraedhawa@gmail.com',
  'sarahjacquier01@gmail.com',
  'celia.blum@hotmail.fr',
  'clain@ursidaeparis.com'
);

$metas_correspondance = array(
  'nickname' => 'public_name',
  'first_name' => 'first_name',
  'last_name' => 'last_name',
  'email' => 'email',
  'description' => 'about',
  'Music' => 'music',
  'Art' => 'art',
  'Design' => 'design',
  'twitter' => 'twitter',
  'facebook'=> 'facebook',
  'headline' => 'headline',
  'user_profil_image' => 'profil_picture'
);

foreach ($bdd->query($sql) as $row):
  if(in_array($row['user_email'], $all_user_email) AND !email_exists($row['user_email'])):
    $user_id = $row['ID'];
    $sqlmeta = "SELECT * FROM MAD_usermeta WHERE user_id = '$user_id'";

    $table = $wpdb->prefix.'users';
    $data = array(
      'user_login' => $row['user_login'],
      'user_pass' => $row['user_pass'],
      'user_nicename' => $row['user_nicename'],
      'user_email' => $row['user_email'],
      'user_url' => $row['user_url'],
      'user_registered' => $row['user_registered'],
      'user_activation_key' => $row['user_activation_key'],
      'user_status' => $row['user_status'],
      'display_name' => $row['display_name'],
    );

    if(!email_exists($row['user_email'])):
      $wpdb->insert($table, $data);
      $artist_id = $wpdb->insert_id;

      foreach ($bdd->query($sqlmeta) as $rowmeta):
        if(array_key_exists($rowmeta['meta_key'], $metas_correspondance)):
          if($rowmeta['meta_key'] == 'user_profil_image'):
            $img_id = $rowmeta['meta_value'];
            $sqlimg = "SELECT * FROM MAD_posts WHERE ID = '$img_id'";

            foreach ($bdd->query($sqlimg) as $rowimg):
              echo $rowimg['guid'].'</br>';
              update_user_meta($artist_id, 'profil_picture', _uploadImageToMediaLibrary(0, $rowimg['guid'], ''));
            endforeach;
          else:
            update_user_meta($artist_id, $metas_correspondance[$rowmeta['meta_key']], $rowmeta['meta_value']);
          endif;
        endif;
      endforeach;

      update_user_meta($artist_id, 'become_artist', true);
      $u = new WP_User($artist_id);
      $u->set_role('subscriber');

      echo $index;
    endif;
  endif;
endforeach;*/

/*$metas_correspondance = array(
  'ign_start_date' => 'start_date',
  'ign_fund_end' => 'end_date',
);

foreach ($bdd->query($sql) as $row):
  echo $row['post_title'].'</br>';
  $index ++;

  $post_id = $row['ID'];
  $sqlmeta = "SELECT * FROM MAD_postmeta WHERE post_id = '$post_id'";

  $project = array(
    'post_title'    => remove_accents($row['post_title']),
    'post_content'  => '',
    'post_status'   => 'draft',
    'post_author'   => 1,
    'post_type'     => 'project'
  );
  $project_id = wp_insert_post( $project );

  foreach ($bdd->query($sqlmeta) as $rowmeta):
    if($rowmeta['meta_key'] == '_thumbnail_id'):
      $img_id = $rowmeta['meta_value'];
      $sqlimg = "SELECT * FROM MAD_posts WHERE ID = '$img_id'";

      foreach ($bdd->query($sqlimg) as $rowimg):
        echo $rowimg['guid'].'</br>';
        set_post_thumbnail($project_id, _uploadImageToMediaLibrary(0, $rowimg['guid'], ''));
      endforeach;
    elseif($rowmeta['meta_key'] == 'ign_project_description'):
      $my_project = array(
        'ID'           => $project_id,
        'post_excerpt' => $rowmeta['meta_value'],
      );
      wp_update_post( $my_project );
    elseif($rowmeta['meta_key'] == 'ign_project_long_description'):
      $my_project = array(
        'ID'           => $project_id,
        'post_content' => $rowmeta['meta_value'],
      );
      wp_update_post( $my_project );
    else:
      update_user_meta($project_id, $metas_correspondance[$rowmeta['meta_key']], $rowmeta['meta_value']);
    endif;
  endforeach;
endforeach;

echo $index;*/

$countries = array(
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Algérie",
  "Allemagne",
  "Andorre",
  "Angola",
  "Antigua-et-Barbuda",
  "Arabie saoudite",
  "Argentine",
  "Arménie",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Belgique",
  "Belize",
  "Bénin",
  "Bhoutan",
  "Biélorussie",
  "Birmanie",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunei",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "République centrafricaine",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "République du Congo",
  "République démocratique du Congo",
  "îles Cook",
  "Corée du Nord",
  "Corée du Sud",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatie",
  "Cuba",
  "Danemark",
  "Djibouti",
  "République dominicaine",
  "Dominique",
  "Égypte",
  "Émirats arabes unis",
  "Équateur",
  "Érythrée",
  "Espagne",
  "Estonie",
  "États-Unis",
  "Éthiopie",
  "Fidji",
  "Finlande",
  "France",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Ghana",
  "Grèce",
  "Grenade",
  "Guatemala",
  "Guinée",
  "Guinée-Bissau",
  "Guinée équatoriale",
  "Guyana",
  "Haïti",
  "Honduras",
  "Hongrie",
  "Inde",
  "Indonésie",
  "Irak",
  "Iran",
  "Irlande",
  "Islande",
  "Israël",
  "Italie",
  "Jamaïque",
  "Japon",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Kirghizistan",
  "Kiribati",
  "Koweït",
  "Laos",
  "Lesotho",
  "Lettonie",
  "Liban",
  "Liberia",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macédoine du Nord",
  "Madagascar",
  "Malaisie",
  "Malawi",
  "Maldives",
  "Mali",
  "Malte",
  "Maroc",
  "îles Marshall",
  "Maurice",
  "Mauritanie",
  "Mexique",
  "Micronésie",
  "Moldavie",
  "Monaco",
  "Mongolie",
  "Monténégro",
  "Mozambique",
  "Namibie",
  "Nauru",
  "Népal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norvège",
  "Nouvelle-Zélande",
  "Oman",
  "Ouganda",
  "Ouzbékistan",
  "Pakistan",
  "Palaos",
  "Palestine",
  "Panamá",
  "Papouasie-Nouvelle-Guinée",
  "Paraguay",
  "Pays-Bas",
  "Pérou",
  "Philippines",
  "Pologne",
  "Portugal",
  "Qatar",
  "Roumanie",
  "Royaume-Uni",
  "Russie",
  "Rwanda",
  "Saint-Christophe-et-Niévès",
  "Saint-Marin",
  "Saint-Vincent-et-les Grenadines",
  "Sainte-Lucie",
  "îles Salomon",
  "Salvador",
  "Samoa",
  "São Tomé-et-Principe",
  "Sénégal",
  "Serbie",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Somalie",
  "Soudan",
  "Soudan du Sud",
  "Sri Lanka",
  "Suède",
  "Suisse",
  "Suriname",
  "Swaziland Eswatini",
  "Syrie",
  "Tadjikistan",
  "Tanzanie",
  "Tchad",
  "République tchèque",
  "Thaïlande",
  "Timor oriental",
  "Togo",
  "Tonga",
  "Trinité-et-Tobago",
  "Tunisie",
  "Turkménistan",
  "Turquie",
  "Tuvalu",
  "Ukraine",
  "Uruguay",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Viêt Nam",
  "Yémen",
  "Zambie",
  "Zimbabwe"
);

if(isset($_POST['mad_admin_seetings'])):
  $active_countries = [];

  foreach($countries as $country):
    if(isset($_POST[sanitize_title($country)])):
      $active_countries[] = $country;
    endif;
  endforeach;

  update_option('active_countries', $active_countries);
endif;

$active_countries = get_option('active_countries');   ?>

<div>
  <h1>Liste des pays disponible</h1>

  <form action="#" method="POST">
    <?php
    foreach($countries as $country):  ?>
      <div class="country_checkbox">
        <input type="checkbox" name="<?php echo sanitize_title($country); ?>" id="<?php echo sanitize_title($country); ?>" <?php echo (in_array($country, $active_countries)) ? 'checked' : '' ; ?>/> <label for="<?php echo sanitize_title($country); ?>"><?php echo $country; ?></label>
      </div><?php
    endforeach; ?>

    <input type="hidden" name="mad_admin_seetings"/>
    <button type="submit" class="button button-primary button-large">Enregistrer</button>
  </form>
</div>
